server:
  port: 9999
  servlet:
    context-path: /uaa
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/ibtech-oauth2?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: pass